name: Test project

on:
  push: 
    branches: 
      - main
    paths-ignore:  
      - .github/workflows/*
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node JS
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node JS
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploying
        run: echo "Deployed..."
        